name: college_app
description: Merged College App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  http_parser: ^4.0.2
  file_picker: ^8.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6 
  lottie: ^3.0.0 # Recommended for animations, added just in case
  image_picker: ^1.0.7 # For picking images, added just in case
  google_fonts: ^6.2.1 # For custom fonts, added just in case

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
